version: '3'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: p0stgr3s
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  app:
    container_name: app
    build: .
    environment:
      NODE_ENV: production
      PORT: 3000
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: p0stgr3s
      TYPEORM_DATABASE: postgres
      TYPEORM_PORT: 5432
      TYPEORM_ENTITIES: dist/modules/**/model/*.js
      JWT_SECRET: 47c3a88d-b090-4390-944a-b0fa581b5e99
      JWT_EXPIRES_IN: 1d
    ports:
      - 3000:3000
    depends_on:
      - db